### PR TITLE
WIP: image classification

### PR DESCRIPTION
**Pull request by jhung0**
2 cases: object table, cell loc, etc. undefined and object table
defined

introduced a new field image_classification, which should be defined as
anything if image classification is desired

### CODE REVIEW

**Comment by daviddao** [comment]
thanks @jhung0 ! I will check it and merge it :)

**Comment by braymp** [comment]
StopIteration exception in https://github.com/CellProfiler/CellProfiler-Analyst/blob/image-classification/cpa/properties.py#L486 if loading a db with no height/width cols ('next' doesn't apply)

**Comment by braymp** [comment]
StopIteration exception in https://github.com/CellProfiler/CellProfiler-Analyst/blob/image-classification/cpa/properties.py#L486 if loading a db with no height/width cols ('next' doesn't apply)

**Comment by jhung0** [comment]
Oh don't merge yet. I'm just trying to make a pull request asap following
Allen's advice

**Comment by jhung0** [comment]
Update: all of Mark's examples work, so should be OK to merge unless there are other examples to try

**Comment by braymp** [comment]
Eventually, all this info will need to go in the manual. If we add the fields to the ExportToDB module in CP, we can document it there too.
Looking at the code, is it correct to say that currently it only works on SQLite dbs?

**Comment by jhung0** [comment]
Ok need to test it out again. No it should work with MySQL too because it
checks db type

**Comment by jhung0** [comment]
Ok @braymp  can you try again?

(Also did a fix for the confusion matrix, which wasn't using stratified cross validation.)

**Comment by daviddao** [comment]
@jhung0 @braymp Any updates on this branch - should I merge it to master?

**Comment by braymp** [comment]
Still need to test; don't merge as yet.

**Comment by braymp** [comment]
The creation of the view seems to be working for MySQL, though not for SQLite.

**Comment by braymp** [comment]
I might have missed if these were already WIP, but when I went to Classifier and fetched, the UI still pulled single cell tiles. Some additions are needed to dbconnect.py to get Classifier to recognize that the new view exists:
* p.object_table and p.image_table need to point to the view.
* p.cell_x_loc and p.cell_y_loc need to point to the width and height cols in the view.

**Comment by braymp** [comment]
Also, when using "Score All" in this case, the computation of enrichment scores should default to unchecked.

**Comment by jhung0** [comment]
You can try it again. What do you mean the computation of enrichment scores
should default to unchecked? Also are you saying you see images of
individual cells? The tiles I see are of the center of the image.

**Comment by braymp** [comment]
Re: enrichment scores: When using Score All, this dialog appears:
image
If the "Report enrichments" is left checked (the current default), you'll get an error b/c there is only one obj per image, and the score makes no sense. So it's best that this box is unchecked/disabled/removed in this instance.

**Comment by braymp** [comment]
I'm also confused as to why, for sqlite, the obj table is dropped rather than a view created. The analysis may have an existing obj table, and you wouldn't want to lose it.

**Comment by jhung0** [comment]
It shouldn't matter if there's an existing obj table because p.object_table
is set to some other name which is the new object table.

**Comment by jhung0** [comment]
I chose tables over views because views are read only
http://www.sqlite.org/omitted.html

**Comment by braymp** [comment]
Also, for reference, this is the pipeline I'm using to test on (remove the .txt extension); it creates both an sqlite and mysql db.
[assay.cppipe.txt](https://github.com/CellProfiler/CellProfiler-Analyst/files/90885/assay.cppipe.txt)
I'm still not able to fetch an entire image in Classifier with the latest changes.

**Comment by braymp** [comment]
I would think that view as read-only is a good thing; we generally don't alter the tables once a CP pipeline makes them anyway. Do you foresee some editing needing to take place?

**Comment by jhung0** [comment]
Can you send your properties files? Are you sure it has
image_classification = 1?
But the new object table needs to be made and values for the object id,
cell_x_loc, cell_y_loc need to be added along with the image table
information.

**Comment by braymp** [comment]
Ah, I had set that field, then re-ran the pipeline, and re-wrote the props file, losing that field; my bad. I get the image tiles now.

**Comment by braymp** [comment]
Another couple of ideas; @jhung0, LMK if this is worth doing:
* Set the image_tile_size field to the height/width (prob whichever is smaller). However, this will make tiles load real slow in the panel, so...
* Adjust the zoom to suit so that the tile is a reasonable size, i.e., in Classifier, View > Image Controls...
My typical workflow when doing QC is to (1) change the image_tile_size field in the props file, and (2) adjust the zoom (something like ~20%) before I even start fetching. Things run pretty smooth after that.

**Comment by jhung0** [comment]
Definitely. It should work now if you set image_width and image_height in
the properties file.

The thing is if you try to set property fields in dbconnect.py, nothing
will happen; you must set fields in properties.py. Thus, image_tile_size
can't be set after you read in column values in the database.

**Comment by jhung0** [comment]
It's nice that you can view images in Classifier, but I think it would make more sense for it to be in ImageViewer too. What do you think @daviddao

**Pull request merged**
