### PR TITLE
Resolve 29 undefined names found by flake8

### PR DESCRIPTION
**Pull request by cclauss**
Add [flake8](http://flake8.pycqa.org) tests to find Python syntax errors and undefined names.

__E901,E999,F821,F822,F823__ are the "_showstopper_" flake8 issues that can halt the runtime with a SyntaxError, NameError, etc. Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

### CODE REVIEW

**Comment by AetherUnbound** [comment]
Oof, there's a lot here. I'd be happy to help resolve some of these!

**Comment by cclauss** [comment]
I have done what I could...  The remaining issues require more knowledge of the existing codebase.

**Comment by cclauss** [comment]
**Temporarily** add __--exit-zero__ to the first flake8 run in __.travis.yml__ so that the existing 29 changes can get reviewed and hopefully merged.  Then a subsequent PR can again remove that first __--exit-zero__ and resolve the remaining 15 undefined names.

**Comment by cclauss** [comment]
Ready for review.

**Comment by AetherUnbound** [comment]
@cclauss Sorry I haven't had my eyes on this repo as much! I'm not as familiar with the Analyst project, myself. I'm taking a look at this now.

**Pull request merged**
